CREATE TABLE "blog_posts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"slug" text NOT NULL,
	"excerpt" text,
	"content" text,
	"thumbnail" text,
	"cover_image" text,
	"category" text,
	"tags" jsonb DEFAULT '[]'::jsonb,
	"status" text DEFAULT 'draft' NOT NULL,
	"author_id" uuid,
	"author_name" text,
	"meta_title" text,
	"meta_description" text,
	"meta_keywords" text,
	"canonical_url" text,
	"og_image" text,
	"view_count" integer DEFAULT 0 NOT NULL,
	"reading_time" integer DEFAULT 0,
	"is_featured" boolean DEFAULT false NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "blog_posts_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "categories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"description" text,
	"icon" text,
	"cover_image" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"meta_title" text,
	"meta_description" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "categories_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "settings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"site_name" text NOT NULL,
	"site_tagline" text,
	"site_description" text,
	"site_url" text NOT NULL,
	"site_logo" text,
	"site_favicon" text,
	"site_language" text DEFAULT 'vi' NOT NULL,
	"site_meta_title" text,
	"site_meta_description" text,
	"site_meta_keywords" text,
	"site_meta_author" text,
	"site_meta_robots" text DEFAULT 'index, follow',
	"site_canonical_url" text,
	"site_og_image" text,
	"site_og_type" text DEFAULT 'website',
	"site_og_locale" text DEFAULT 'vi_VN',
	"site_google_analytics_id" text,
	"site_google_tag_manager_id" text,
	"site_facebook_pixel_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "products" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"tagline" text,
	"description" text,
	"content" text,
	"category_id" uuid,
	"type" text DEFAULT 'premium' NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"thumbnail" text,
	"cover_image" text,
	"images" jsonb DEFAULT '[]'::jsonb,
	"video_url" text,
	"demo_url" text,
	"source_url" text,
	"documentation_url" text,
	"changelog_url" text,
	"tech_stack" jsonb DEFAULT '[]'::jsonb,
	"tags" jsonb DEFAULT '[]'::jsonb,
	"frameworks" jsonb DEFAULT '[]'::jsonb,
	"price" numeric(12, 0) DEFAULT '0' NOT NULL,
	"sale_price" numeric(12, 0),
	"currency" text DEFAULT 'VND' NOT NULL,
	"version" text DEFAULT '1.0.0',
	"compatibility" text,
	"requirements" text,
	"file_size" text,
	"last_updated_version" timestamp with time zone,
	"view_count" integer DEFAULT 0 NOT NULL,
	"download_count" integer DEFAULT 0 NOT NULL,
	"purchase_count" integer DEFAULT 0 NOT NULL,
	"rating" numeric(2, 1) DEFAULT '0',
	"rating_count" integer DEFAULT 0 NOT NULL,
	"features" jsonb DEFAULT '[]'::jsonb,
	"highlights" jsonb DEFAULT '[]'::jsonb,
	"warranty_months" integer DEFAULT 3,
	"support_email" text,
	"support_included" boolean DEFAULT true NOT NULL,
	"meta_title" text,
	"meta_description" text,
	"meta_keywords" text,
	"author_id" uuid,
	"is_featured" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "products_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "username" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "provider" text DEFAULT 'local' NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "provider_id" text;--> statement-breakpoint
ALTER TABLE "blog_posts" ADD CONSTRAINT "blog_posts_author_id_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_author_id_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;