export interface Bank {
  id: number;
  name: string;
  code: string;
  bin: string;
  shortName: string;
  logo: string;
  transferSupported: number;
  lookupSupported: number;
  short_name: string;
  support: number;
  isTransfer: number;
  swift_code: string | null;
}

export interface BankResponse {
  version: string;
  messgae: string;
  data: Bank[];
}
export const banks: BankResponse = {
  version: "1.0.0",
  messgae: "List banks for Vani Studio MMO Ecosystem 2025.",
  data: [
    {
      id: 17,
      name: "Ngân hàng TMCP Công thương Việt Nam",
      code: "ICB",
      bin: "970415",
      shortName: "VietinBank",
      logo: "https://storage.vanistudio.com/smm/banks/970415.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "VietinBank",
      support: 3,
      isTransfer: 1,
      swift_code: "ICBVVNVX",
    },
    {
      id: 43,
      name: "Ngân hàng TMCP Ngoại Thương Việt Nam",
      code: "VCB",
      bin: "970436",
      shortName: "Vietcombank",
      logo: "https://storage.vanistudio.com/smm/banks/970436.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "Vietcombank",
      support: 3,
      isTransfer: 1,
      swift_code: "BFTVVNVX",
    },
    {
      id: 4,
      name: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam",
      code: "BIDV",
      bin: "970418",
      shortName: "BIDV",
      logo: "https://storage.vanistudio.com/smm/banks/970418.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "BIDV",
      support: 3,
      isTransfer: 1,
      swift_code: "BIDVVNVX",
    },
    {
      id: 42,
      name: "Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam",
      code: "VBA",
      bin: "970405",
      shortName: "Agribank",
      logo: "https://storage.vanistudio.com/smm/banks/970405.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "Agribank",
      support: 3,
      isTransfer: 1,
      swift_code: "VBAAVNVX",
    },
    {
      id: 26,
      name: "Ngân hàng TMCP Phương Đông",
      code: "OCB",
      bin: "970448",
      shortName: "OCB",
      logo: "https://storage.vanistudio.com/smm/banks/970448.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "OCB",
      support: 3,
      isTransfer: 1,
      swift_code: "ORCOVNVX",
    },
    {
      id: 21,
      name: "Ngân hàng TMCP Quân đội",
      code: "MB",
      bin: "970422",
      shortName: "MBBank",
      logo: "https://storage.vanistudio.com/smm/banks/970422.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "MBBank",
      support: 3,
      isTransfer: 1,
      swift_code: "MSCBVNVX",
    },
    {
      id: 38,
      name: "Ngân hàng TMCP Kỹ thương Việt Nam",
      code: "TCB",
      bin: "970407",
      shortName: "Techcombank",
      logo: "https://storage.vanistudio.com/smm/banks/970407.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "Techcombank",
      support: 3,
      isTransfer: 1,
      swift_code: "VTCBVNVX",
    },
    {
      id: 2,
      name: "Ngân hàng TMCP Á Châu",
      code: "ACB",
      bin: "970416",
      shortName: "ACB",
      logo: "https://storage.vanistudio.com/smm/banks/970416.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "ACB",
      support: 3,
      isTransfer: 1,
      swift_code: "ASCBVNVX",
    },
    {
      id: 47,
      name: "Ngân hàng TMCP Việt Nam Thịnh Vượng",
      code: "VPB",
      bin: "970432",
      shortName: "VPBank",
      logo: "https://storage.vanistudio.com/smm/banks/970432.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "VPBank",
      support: 3,
      isTransfer: 1,
      swift_code: "VPBKVNVX",
    },
    {
      id: 39,
      name: "Ngân hàng TMCP Tiên Phong",
      code: "TPB",
      bin: "970423",
      shortName: "TPBank",
      logo: "https://storage.vanistudio.com/smm/banks/970423.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "TPBank",
      support: 3,
      isTransfer: 1,
      swift_code: "TPBVVNVX",
    },
    {
      id: 36,
      name: "Ngân hàng TMCP Sài Gòn Thương Tín",
      code: "STB",
      bin: "970403",
      shortName: "Sacombank",
      logo: "https://storage.vanistudio.com/smm/banks/970403.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "Sacombank",
      support: 3,
      isTransfer: 1,
      swift_code: "SGTTVNVX",
    },
    {
      id: 12,
      name: "Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh",
      code: "HDB",
      bin: "970437",
      shortName: "HDBank",
      logo: "https://storage.vanistudio.com/smm/banks/970437.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "HDBank",
      support: 3,
      isTransfer: 1,
      swift_code: "HDBCVNVX",
    },
    {
      id: 44,
      name: "Ngân hàng TMCP Bản Việt",
      code: "VCCB",
      bin: "970454",
      shortName: "VietCapitalBank",
      logo: "https://storage.vanistudio.com/smm/banks/970454.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "VietCapitalBank",
      support: 3,
      isTransfer: 1,
      swift_code: "VCBCVNVX",
    },
    {
      id: 31,
      name: "Ngân hàng TMCP Sài Gòn",
      code: "SCB",
      bin: "970429",
      shortName: "SCB",
      logo: "https://storage.vanistudio.com/smm/banks/970429.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "SCB",
      support: 3,
      isTransfer: 1,
      swift_code: "SACLVNVX",
    },
    {
      id: 45,
      name: "Ngân hàng TMCP Quốc tế Việt Nam",
      code: "VIB",
      bin: "970441",
      shortName: "VIB",
      logo: "https://storage.vanistudio.com/smm/banks/970441.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "VIB",
      support: 3,
      isTransfer: 1,
      swift_code: "VNIBVNVX",
    },
    {
      id: 10,
      name: "Ngân hàng TMCP Xuất Nhập khẩu Việt Nam",
      code: "EIB",
      bin: "970431",
      shortName: "Eximbank",
      logo: "https://storage.vanistudio.com/smm/banks/970431.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "Eximbank",
      support: 3,
      isTransfer: 1,
      swift_code: "EBVIVNVX",
    },
    {
      id: 22,
      name: "Ngân hàng TMCP Hàng Hải Việt Nam",
      code: "MSB",
      bin: "970426",
      shortName: "MSB",
      logo: "https://storage.vanistudio.com/smm/banks/970426.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "MSB",
      support: 3,
      isTransfer: 1,
      swift_code: "MCOBVNVX",
    },
    {
      id: 57,
      name: "Tổng Công ty Dịch vụ số Viettel - Chi nhánh tập đoàn công nghiệp viễn thông Quân Đội",
      code: "VTLMONEY",
      bin: "971005",
      shortName: "ViettelMoney",
      logo: "https://storage.vanistudio.com/smm/banks/971005.png",
      transferSupported: 0,
      lookupSupported: 1,
      short_name: "ViettelMoney",
      support: 0,
      isTransfer: 0,
      swift_code: null,
    },
    {
      id: 58,
      name: "Ngân hàng số Timo by Ban Viet Bank (Timo by Ban Viet Bank)",
      code: "TIMO",
      bin: "963388",
      shortName: "Timo",
      logo: "https://storage.vanistudio.com/smm/banks/963388.png",
      transferSupported: 1,
      lookupSupported: 0,
      short_name: "Timo",
      support: 0,
      isTransfer: 1,
      swift_code: null,
    },
    {
      id: 34,
      name: "Ngân hàng TMCP Sài Gòn Công Thương",
      code: "SGICB",
      bin: "970400",
      shortName: "SaigonBank",
      logo: "https://storage.vanistudio.com/smm/banks/970400.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "SaigonBank",
      support: 3,
      isTransfer: 1,
      swift_code: "SBITVNVX",
    },
    {
      id: 3,
      name: "Ngân hàng TMCP Bắc Á",
      code: "BAB",
      bin: "970409",
      shortName: "BacABank",
      logo: "https://storage.vanistudio.com/smm/banks/970409.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "BacABank",
      support: 3,
      isTransfer: 1,
      swift_code: "NASCVNVX",
    },
    {
      id: 27,
      name: "Ngân hàng TNHH MTV Việt Nam Hiện Đại",
      code: "MBV",
      bin: "970414",
      shortName: "MBV",
      logo: "https://storage.vanistudio.com/smm/banks/970414.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "MBV",
      support: 3,
      isTransfer: 1,
      swift_code: "OCBKUS3M",
    },
    {
      id: 37,
      name: "Ngân hàng TNHH MTV Shinhan Việt Nam",
      code: "SHBVN",
      bin: "970424",
      shortName: "ShinhanBank",
      logo: "https://storage.vanistudio.com/smm/banks/970424.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "ShinhanBank",
      support: 3,
      isTransfer: 1,
      swift_code: "SHBKVNVX",
    },
    {
      id: 1,
      name: "Ngân hàng TMCP An Bình",
      code: "ABB",
      bin: "970425",
      shortName: "ABBANK",
      logo: "https://storage.vanistudio.com/smm/banks/970425.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "ABBANK",
      support: 3,
      isTransfer: 1,
      swift_code: "ABBKVNVX",
    },
    {
      id: 41,
      name: "Ngân hàng TMCP Việt Á",
      code: "VAB",
      bin: "970427",
      shortName: "VietABank",
      logo: "https://storage.vanistudio.com/smm/banks/970427.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "VietABank",
      support: 3,
      isTransfer: 1,
      swift_code: "VNACVNVX",
    },
    {
      id: 23,
      name: "Ngân hàng TMCP Nam Á",
      code: "NAB",
      bin: "970428",
      shortName: "NamABank",
      logo: "https://storage.vanistudio.com/smm/banks/970428.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "NamABank",
      support: 3,
      isTransfer: 1,
      swift_code: "NAMAVNVX",
    },
    {
      id: 29,
      name: "Ngân hàng TMCP Thịnh vượng và Phát triển",
      code: "PGB",
      bin: "970430",
      shortName: "PGBank",
      logo: "https://storage.vanistudio.com/smm/banks/970430.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "PGBank",
      support: 3,
      isTransfer: 1,
      swift_code: "PGBLVNVX",
    },
    {
      id: 46,
      name: "Ngân hàng TMCP Việt Nam Thương Tín",
      code: "VIETBANK",
      bin: "970433",
      shortName: "VietBank",
      logo: "https://storage.vanistudio.com/smm/banks/970433.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "VietBank",
      support: 3,
      isTransfer: 1,
      swift_code: "VNTTVNVX",
    },
    {
      id: 5,
      name: "Ngân hàng TMCP Bảo Việt",
      code: "BVB",
      bin: "970438",
      shortName: "BaoVietBank",
      logo: "https://storage.vanistudio.com/smm/banks/970438.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "BaoVietBank",
      support: 3,
      isTransfer: 1,
      swift_code: "BVBVVNVX",
    },
    {
      id: 33,
      name: "Ngân hàng TMCP Đông Nam Á",
      code: "SEAB",
      bin: "970440",
      shortName: "SeABank",
      logo: "https://storage.vanistudio.com/smm/banks/970440.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "SeABank",
      support: 3,
      isTransfer: 1,
      swift_code: "SEAVVNVX",
    },
    {
      id: 20,
      name: "Ngân hàng TMCP Lộc Phát Việt Nam",
      code: "LPB",
      bin: "970449",
      shortName: "LPBank",
      logo: "https://storage.vanistudio.com/smm/banks/970449.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "LPBank",
      support: 3,
      isTransfer: 1,
      swift_code: "LVBKVNVX",
    },
    {
      id: 19,
      name: "Ngân hàng TMCP Kiên Long",
      code: "KLB",
      bin: "970452",
      shortName: "KienLongBank",
      logo: "https://storage.vanistudio.com/smm/banks/970452.png",
      transferSupported: 1,
      lookupSupported: 1,
      short_name: "KienLongBank",
      support: 3,
      isTransfer: 1,
      swift_code: "KLBKVNVX",
    },
    {
      id: 9,
      name: "Ngân hàng TNHH MTV Số Vikki",
      code: "Vikki",
      bin: "970406",
      shortName: "Vikki",
      logo: "https://cdn.vietqr.io/img/Vikki.png",
      transferSupported: 0,
      lookupSupported: 1,
      short_name: "Vikki",
      support: 0,
      isTransfer: 0,
      swift_code: "EACBVNVX",
    },
  ],
};
